version: '3.8'

services:
  web:
    build: .
    container_name: quanlymuontrasach_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: quanlymuontrasach_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: QuanLyNhaSach
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
